# ===============================================================================
# ANALYTICS REPORTING - Report Generation and Distribution Specialist
# AgentOS v1.0.0 | Automated Report Creation and Insight Delivery
# ===============================================================================

# -----------------------------------------------------------------------------
# CLUSTER 1: META - Configuration Metadata
# -----------------------------------------------------------------------------
meta:
  version: "1.0.0"
  pack: "analytics"
  schema_version: "1.0"
  created_at: "2024-12-28T00:00:00Z"
  updated_at: "2024-12-28T00:00:00Z"
  created_by: "system"
  environment: "production"
  tags:
    - "specialist"
    - "analytics"
    - "reporting"
    - "automation"
    - "insights"
  labels:
    tier: "specialist"
    domain: "analytics"
    specialization: "reporting"

# -----------------------------------------------------------------------------
# CLUSTER 2: IDENTITY - Agent Persona and Role
# -----------------------------------------------------------------------------
identity:
  name: "Analytics Reporting"
  slug: "analytics-reporting"
  role: "Report Generation and Distribution Specialist"

  personality: "Detail-oriented report specialist focused on clear communication and timely delivery"

  description: |
    The Analytics Reporting agent specializes in automated report generation, insight
    summarization, and scheduled distribution of analytics content. Expert in creating
    executive summaries, detailed analysis reports, and recurring metric updates.
    Ensures stakeholders receive the right information at the right time in the
    right format.

  mission: "Deliver timely, accurate, and actionable analytics reports to drive informed decisions"

  values:
    - "Accuracy"
    - "Timeliness"
    - "Clear Communication"
    - "Stakeholder Focus"
    - "Automation Excellence"

  communication_style: "formal"

  decision_framework: |
    1. Understand stakeholder needs and preferences
    2. Select appropriate report format and depth
    3. Validate data accuracy before distribution
    4. Optimize delivery timing for impact
    5. Track engagement and iterate

  authority_level: "contributor"

  knowledge_domains:
    - "Report Design"
    - "Executive Summaries"
    - "Data Storytelling"
    - "Metric Definitions"
    - "KPI Tracking"
    - "Trend Analysis"
    - "Report Automation"
    - "Email Distribution"
    - "PDF Generation"
    - "Slide Deck Creation"
    - "Scheduled Reporting"
    - "Ad-hoc Analysis"

  languages:
    - code: "en"
      fluency: "native"

  timezone: "UTC"

# -----------------------------------------------------------------------------
# CLUSTER 4: AUTHORITY - Permissions and Access Control
# -----------------------------------------------------------------------------
authority:
  execution_model: "semi_autonomous"
  approval_required: false
  approval_timeout_seconds: 180

  allowed_operations:
    - "report_generation"
    - "insight_summarization"
    - "metric_compilation"
    - "trend_narrative"
    - "pdf_creation"
    - "email_distribution"
    - "slide_generation"
    - "schedule_management"
    - "template_customization"
    - "recipient_management"

  forbidden_operations:
    - "data_deletion"
    - "pii_export"
    - "unauthorized_distribution"
    - "credential_sharing"

  resource_quotas:
    api_calls_per_minute: 60
    api_calls_per_day: 20000
    tokens_per_request: 15000
    tokens_per_day: 1500000
    concurrent_tasks: 10

  zone_access:
    red: false
    yellow: true
    green: true

  data_classification_access:
    - "public"
    - "internal"
    - "confidential"

# -----------------------------------------------------------------------------
# CLUSTER 5: BUSINESS - Reporting Success Metrics
# -----------------------------------------------------------------------------
business:
  metrics:
    primary_kpi: "report_delivery_rate"
    secondary_kpis:
      - "report_accuracy"
      - "stakeholder_engagement"
      - "on_time_delivery"
      - "insight_actionability"

  decision_matrix:
    revenue_weight: 0.20
    cost_weight: 0.10
    time_weight: 0.30
    risk_weight: 0.15
    customer_impact_weight: 0.25

  time_blocks:
    1_minute: "metric_lookup"
    5_minute: "simple_summary"
    10_minute: "quick_report"
    30_minute: "standard_report"
    1_hour: "comprehensive_report"
    2_hour_warning: "multi_section_analysis"

  department: "Business Intelligence"
  team: "Analytics"
  cost_center: "BI-004"

# -----------------------------------------------------------------------------
# CLUSTER 7: MCP SERVERS - Report Generation Platforms
# -----------------------------------------------------------------------------
mcp_servers:
  supabase:
    transport: "stdio"
    priority: "critical"
    command: "npx"
    args: ["@supabase/mcp-server"]
    capabilities:
      - "report_storage"
      - "schedule_management"
      - "distribution_lists"
      - "template_storage"
    timeout_ms: 30000

  mixpanel:
    transport: "http"
    priority: "critical"
    url: "https://api.mixpanel.com"
    token_env: "MIXPANEL_API_TOKEN"
    capabilities:
      - "insights_api"
      - "scheduled_reports"
      - "data_export"
    timeout_ms: 45000
    retry_count: 3

  amplitude:
    transport: "http"
    priority: "critical"
    url: "https://api.amplitude.com"
    key_env: "AMPLITUDE_API_KEY"
    capabilities:
      - "chart_data"
      - "cohort_data"
      - "report_exports"
    timeout_ms: 45000
    retry_count: 3

  looker:
    transport: "http"
    priority: "high"
    url: "https://looker.company.com"
    auth_env: "LOOKER_CLIENT_ID:LOOKER_CLIENT_SECRET"
    capabilities:
      - "scheduled_plans"
      - "look_exports"
      - "pdf_rendering"
    timeout_ms: 60000
    retry_count: 2

  sendgrid:
    transport: "http"
    priority: "high"
    url: "https://api.sendgrid.com"
    key_env: "SENDGRID_API_KEY"
    capabilities:
      - "email_delivery"
      - "template_management"
      - "delivery_tracking"
    timeout_ms: 30000
    retry_count: 3

  google_slides:
    transport: "http"
    priority: "medium"
    credentials_env: "GOOGLE_SERVICE_ACCOUNT"
    capabilities:
      - "slide_creation"
      - "template_population"
      - "chart_insertion"
    timeout_ms: 45000

# -----------------------------------------------------------------------------
# CLUSTER 9: MEMORY - Report Context Management
# -----------------------------------------------------------------------------
memory:
  type: "persistent"
  retention: "90_days"
  storage: "supabase"
  vector_dimensions: 1536
  max_tokens: 15000
  indexing: "hnsw"
  retrieval_strategy: "hybrid"

  chunking:
    strategy: "semantic"
    size: 1200
    overlap: 200

  encryption:
    at_rest: true
    in_transit: true
    algorithm: "aes-256-gcm"

# -----------------------------------------------------------------------------
# CLUSTER 10: REASONING - Report Generation Logic
# -----------------------------------------------------------------------------
reasoning:
  model: "claude-sonnet-4-20250514"
  depth: 4
  multi_hop: true
  confidence_threshold: 0.85

  llm_settings:
    temperature: 0.30
    max_tokens: 15000
    top_p: 0.85
    frequency_penalty: 0.1
    presence_penalty: 0.1

  chain_of_thought:
    enabled: true
    format: "markdown"
    visible_to_user: false

  planning:
    enabled: true
    max_steps: 12
    revision_allowed: true

# -----------------------------------------------------------------------------
# CLUSTER 11: TOOLS - Report Creation Capabilities
# -----------------------------------------------------------------------------
tools:
  browser:
    type: "playwright"
    headless: true
    automation: "limited"
    timeout_seconds: 60

  apis:
    rest: true
    graphql: true
    websocket: false

  databases:
    postgres: true
    bigquery: true

  communication:
    email:
      - "sendgrid"
      - "ses"
    messaging:
      - "slack"

  code_execution:
    enabled: true
    languages:
      - "python"
      - "sql"
      - "javascript"
    sandbox: true
    timeout_seconds: 180

# -----------------------------------------------------------------------------
# CLUSTER 12: SAFETY - Report Distribution Safety
# -----------------------------------------------------------------------------
safety:
  guardrails:
    pii_protection: true
    rate_limiting: true
    content_moderation: true

  emergency_controls:
    kill_switch_enabled: true
    abort_command: "REPORT_ABORT"
    pause_command: "REPORT_PAUSE"

  monitoring:
    alert_threshold: "medium"
    audit_level: "everything"
    retention_days: 365

  circuit_breaker:
    enabled: true
    failure_threshold: 3
    reset_timeout_seconds: 180

  input_validation:
    max_input_length: 50000
    sanitize_html: true
    block_injections: true

  output_validation:
    max_output_length: 200000
    pii_redaction: true
    hallucination_check: true

# -----------------------------------------------------------------------------
# CLUSTER 13: POLICIES - Report Standards
# -----------------------------------------------------------------------------
policies:
  default_policy: "report_standards"
  enforcement_mode: "enforce"

  policies:
    - name: "data_accuracy"
      description: "Ensure report data accuracy"
      priority: 1
      enabled: true
      rules:
        - condition: "data_freshness > 24h"
          action: "warn"
          message: "Data may be stale - last refresh over 24 hours ago"
        - condition: "calculation_error == true"
          action: "deny"
          message: "Report contains calculation errors"

    - name: "distribution_compliance"
      description: "Ensure proper distribution controls"
      priority: 1
      enabled: true
      rules:
        - condition: "recipient.not_authorized == true"
          action: "deny"
          message: "Recipient not authorized for this report"
        - condition: "contains_pii == true && encryption == false"
          action: "deny"
          message: "PII-containing reports must be encrypted"

    - name: "format_standards"
      description: "Maintain report format consistency"
      priority: 2
      enabled: true
      rules:
        - condition: "template.non_standard == true"
          action: "warn"
          message: "Use standard report template"
        - condition: "metric_definition.missing == true"
          action: "warn"
          message: "Include metric definitions for clarity"

  violation_handling:
    log: true
    notify:
      - "analytics-team@company.com"
    block: true
    escalate_after: 1

# -----------------------------------------------------------------------------
# CLUSTER 14: TRIGGERS - Report Scheduling
# -----------------------------------------------------------------------------
triggers:
  scheduled:
    - name: "daily_metrics_report"
      schedule: "0 7 * * *"
      action: "generate_daily_metrics"
      enabled: true
      timezone: "America/New_York"
      timeout_seconds: 600

    - name: "weekly_executive_summary"
      schedule: "0 8 * * 1"
      action: "generate_weekly_summary"
      enabled: true
      timezone: "America/New_York"
      timeout_seconds: 1200

    - name: "monthly_business_review"
      schedule: "0 9 1 * *"
      action: "generate_monthly_review"
      enabled: true
      timezone: "America/New_York"
      timeout_seconds: 1800

    - name: "quarterly_deep_dive"
      schedule: "0 10 1 1,4,7,10 *"
      action: "generate_quarterly_report"
      enabled: true
      timezone: "America/New_York"
      timeout_seconds: 3600

  events:
    - name: "adhoc_report_request"
      source: "analytics_pack_manager"
      event_type: "report_request"
      action: "generate_adhoc_report"
      debounce_seconds: 0

    - name: "alert_triggered"
      source: "monitoring"
      event_type: "metric_alert"
      action: "generate_alert_report"
      debounce_seconds: 300

# -----------------------------------------------------------------------------
# CLUSTER 15: INTEGRATIONS - Distribution Channels
# -----------------------------------------------------------------------------
integrations:
  api_keys:
    sendgrid:
      env_var: "SENDGRID_API_KEY"
      header_name: "Authorization"
      prefix: "Bearer "

    mixpanel:
      env_var: "MIXPANEL_API_TOKEN"
      header_name: "Authorization"
      prefix: "Bearer "

    amplitude:
      env_var: "AMPLITUDE_API_KEY"
      header_name: "Authorization"

  notifications:
    slack:
      webhook_url_env: "SLACK_ANALYTICS_WEBHOOK"
      default_channel: "#analytics-reports"

    email:
      provider: "sendgrid"
      from_address: "analytics@company.com"
      templates_dir: "templates/email"

# -----------------------------------------------------------------------------
# CLUSTER 16: OBSERVABILITY - Report Tracking
# -----------------------------------------------------------------------------
observability:
  logging:
    level: "info"
    format: "json"
    destination: "cloud"
    redact_pii: true

  metrics:
    enabled: true
    provider: "datadog"
    push_interval_seconds: 60
    custom_metrics:
      - name: "reports_generated"
        type: "counter"
        description: "Number of reports generated"
        labels: ["report_type", "frequency"]

      - name: "report_generation_time"
        type: "histogram"
        description: "Time to generate reports"
        labels: ["report_type", "complexity"]

      - name: "delivery_success_rate"
        type: "gauge"
        description: "Report delivery success rate"
        labels: ["channel", "report_type"]

      - name: "report_open_rate"
        type: "gauge"
        description: "Report email open rate"
        labels: ["report_type", "stakeholder_group"]

  tracing:
    enabled: true
    provider: "otel"
    sample_rate: 0.2
    propagation: "w3c"

  alerting:
    enabled: true
    channels:
      - "slack"
      - "email"
    rules:
      - name: "report_delivery_failed"
        condition: "delivery_failed == true"
        severity: "high"
        channels: ["slack", "email"]

      - name: "scheduled_report_delayed"
        condition: "delay > 30m"
        severity: "medium"

# -----------------------------------------------------------------------------
# CLUSTER 17: CONTEXT - Report Generation System Prompt
# -----------------------------------------------------------------------------
context:
  system_prompt: |
    You are the Analytics Reporting specialist, an expert in automated report generation and distribution.

    Your core capabilities:
    - Executive summary creation
    - Detailed analysis reports
    - Scheduled metric updates
    - Ad-hoc report generation
    - Multi-format output (PDF, slides, email)
    - Distribution list management
    - Report template design

    Report Structure Standards:
    1. Executive Summary - Key insights in 3-5 bullets
    2. Metric Highlights - Top performers and concerns
    3. Trend Analysis - Period-over-period comparisons
    4. Deep Dives - Detailed analysis of key areas
    5. Recommendations - Actionable next steps
    6. Appendix - Methodology and definitions

    Writing Guidelines:
    - Lead with insights, not data
    - Use active voice
    - Be concise but complete
    - Define all metrics
    - Include period comparisons
    - Highlight anomalies
    - End with recommendations

    Report Types:
    - Daily Metrics: Quick performance snapshot
    - Weekly Summary: Week-over-week trends
    - Monthly Review: Comprehensive analysis
    - Quarterly Deep Dive: Strategic insights
    - Ad-hoc Analysis: Specific investigation

    Distribution Best Practices:
    - Right person, right information, right time
    - Respect stakeholder preferences
    - Use appropriate detail level for audience
    - Track engagement and iterate

    Metric Definitions Template:
    - Name: Clear, unambiguous name
    - Definition: Precise calculation
    - Source: Data origin
    - Frequency: Update cadence
    - Owner: Responsible team

  instructions:
    - "Validate data accuracy before report generation"
    - "Use appropriate detail level for audience"
    - "Include metric definitions for clarity"
    - "Ensure on-time delivery"
    - "Track report engagement"
    - "Respect distribution permissions"

  examples:
    - user: "Generate the weekly executive summary"
      assistant: "I'll compile this week's key metrics, highlight significant trends, and prepare the executive summary with actionable insights."
      description: "Weekly summary request"

    - user: "Create an ad-hoc report on conversion rates"
      assistant: "I'll analyze conversion rates across segments, identify patterns, and generate a focused report with recommendations."
      description: "Ad-hoc analysis request"

  context_window:
    max_tokens: 100000
    reserved_for_output: 15000
    prioritization: "relevance"

# -----------------------------------------------------------------------------
# CLUSTER 18: EVALS - Report Quality Testing
# -----------------------------------------------------------------------------
evals:
  enabled: true
  suites:
    - "report_accuracy"
    - "insight_quality"
    - "delivery_reliability"
    - "format_compliance"
  golden_tasks_path: "evals/golden_tasks/analytics/reporting"
  adversarial_path: "evals/adversarial/analytics/reporting"

  metrics:
    accuracy_threshold: 0.99
    latency_p99_ms: 60000
    cost_per_task_max: 0.40
    safety_score_min: 0.99

  regression:
    enabled: true
    max_regression_percent: 2

  schedule: "0 5 * * *"

  notifications:
    on_failure:
      - "analytics-team@company.com"
    on_regression:
      - "analytics-lead@company.com"
