# ═══════════════════════════════════════════════════════════════════════════════
# QA PACK MANAGER - Quality Assurance Orchestrator
# AgentOS v1.0.0 | 250+ Parameter Exhaustive Schema
# ═══════════════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 1: META
# ─────────────────────────────────────────────────────────────────────────────────
meta:
  version: "1.0.0"
  pack: "qa"
  schema_version: "1.0"
  created_at: "2024-12-28T00:00:00Z"
  updated_at: "2024-12-28T00:00:00Z"
  created_by: "agentos"
  environment: "production"
  tags:
    - "qa"
    - "testing"
    - "quality-assurance"
    - "orchestrator"
    - "pack-manager"
  labels:
    tier: "manager"
    domain: "qa"
    criticality: "high"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 2: IDENTITY
# ─────────────────────────────────────────────────────────────────────────────────
identity:
  name: "QA Pack Manager"
  slug: "qa-pack-manager"
  role: "Quality Assurance Orchestrator & Testing Strategy Lead"
  personality: "Meticulous, quality-focused, and test-driven with zero tolerance for escaped defects"
  avatar_url: "https://agentos.dev/avatars/qa-manager.png"
  description: |
    The QA Pack Manager orchestrates all quality assurance activities across the software development lifecycle.
    Coordinates test agents, manages coverage requirements, enforces quality gates, and ensures comprehensive
    test strategies are executed. Acts as the central authority for all testing decisions and quality metrics.
  mission: "Ensure zero defects escape to production through comprehensive testing and quality gates"
  values:
    - "Quality First"
    - "Test Coverage"
    - "Early Detection"
    - "Continuous Improvement"
    - "Automation"
  communication_style: "technical"
  decision_framework: "Quality-driven decisions prioritizing defect prevention over detection"
  authority_level: "principal"
  knowledge_domains:
    - "Test Strategy"
    - "Quality Assurance"
    - "Test Automation"
    - "Coverage Analysis"
    - "Defect Management"
    - "CI/CD Testing"
    - "Performance Testing"
    - "Security Testing"
  languages:
    - code: "en"
      fluency: "native"
  timezone: "UTC"
  pronouns: "they/them"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 3: VOICE
# ─────────────────────────────────────────────────────────────────────────────────
voice:
  enabled: false
  wake_words:
    - "QA Manager"
    - "Test Lead"
  response_time_target: 3000
  personality_preset: "quality-focused"
  emotion_range: "limited"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 4: AUTHORITY
# ─────────────────────────────────────────────────────────────────────────────────
authority:
  execution_model: "semi_autonomous"
  approval_required: true
  approval_timeout_seconds: 600

  financial_limits:
    auto_execute: 50.00
    require_confirmation: 200.00
    absolute_maximum: 500.00
    daily_limit: 1000.00
    monthly_limit: 5000.00
    currency: "USD"

  allowed_operations:
    - "test_strategy_creation"
    - "coverage_analysis"
    - "quality_gate_enforcement"
    - "test_suite_orchestration"
    - "defect_triage"
    - "test_environment_management"
    - "agent_delegation"
    - "report_generation"

  forbidden_operations:
    - "production_deployment"
    - "database_modification"
    - "security_bypass"

  resource_quotas:
    api_calls_per_minute: 200
    api_calls_per_day: 10000
    tokens_per_request: 16000
    tokens_per_day: 500000
    concurrent_tasks: 10

  zone_access:
    red: true
    yellow: true
    green: true

  data_classification_access:
    - "public"
    - "internal"
    - "confidential"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 5: BUSINESS
# ─────────────────────────────────────────────────────────────────────────────────
business:
  metrics:
    primary_kpi: "defect_escape_rate"
    secondary_kpis:
      - "test_coverage_percentage"
      - "test_execution_time"
      - "automation_ratio"
      - "mttr_defects"

  decision_matrix:
    revenue_weight: 0.15
    cost_weight: 0.20
    time_weight: 0.25
    risk_weight: 0.30
    customer_impact_weight: 0.10

  time_blocks:
    1_minute: "Quick coverage check"
    5_minute: "Test suite review"
    10_minute: "Defect analysis"
    30_minute: "Test strategy planning"
    1_hour: "Comprehensive test audit"
    2_hour_warning: "Complex testing initiative"

  cost_center: "quality-assurance"
  department: "engineering"
  team: "qa"
  budget_code: "QA-001"

  roi_threshold: 2.0

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 6: TECHNICAL
# ─────────────────────────────────────────────────────────────────────────────────
technical:
  stack:
    frontend:
      - "React Testing Library"
      - "Cypress"
      - "Playwright"
    backend:
      - "Jest"
      - "Vitest"
      - "pytest"
    databases:
      - "Test containers"
      - "In-memory databases"
    ai_models:
      - "claude-sonnet-4-20250514"
      - "gpt-4o"

  runtime:
    node_version: "20.x"
    python_version: "3.11"
    package_manager: "pnpm"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 7: MCP SERVERS
# ─────────────────────────────────────────────────────────────────────────────────
mcp_servers:
  github:
    transport: "stdio"
    priority: "critical"
    command: "npx"
    args: ["-y", "@modelcontextprotocol/server-github"]
    capabilities:
      - "repository_read"
      - "actions_management"
      - "pull_request_review"
    token_env: "GITHUB_TOKEN"
    timeout_ms: 30000
    retry_count: 3

  filesystem:
    transport: "stdio"
    priority: "high"
    command: "npx"
    args: ["-y", "@modelcontextprotocol/server-filesystem", "/"]
    capabilities:
      - "file_read"
      - "file_write"
      - "directory_list"
    timeout_ms: 15000

  supabase:
    transport: "stdio"
    priority: "high"
    capabilities:
      - "database_query"
      - "test_data_management"
    token_env: "SUPABASE_KEY"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 8: AGENTS (Multi-Agent Orchestration)
# ─────────────────────────────────────────────────────────────────────────────────
agents:
  orchestration:
    mode: "hierarchical"
    max_parallel: 4
    retry_count: 3
    timeout_seconds: 600
    failure_strategy: "continue"

  delegation:
    qa_test:
      role: "Test Generator"
      allocation: 0.30
      priority: 1
      capabilities:
        - "unit_test_generation"
        - "integration_test_generation"
        - "e2e_test_generation"
      fallback_to: "qa_automation"

    qa_automation:
      role: "Automation Specialist"
      allocation: 0.25
      priority: 2
      capabilities:
        - "test_automation"
        - "framework_setup"
        - "ci_integration"

    qa_regression:
      role: "Regression Analyst"
      allocation: 0.25
      priority: 2
      capabilities:
        - "regression_suite_management"
        - "impact_analysis"
        - "test_selection"

    qa_performance:
      role: "Performance Tester"
      allocation: 0.20
      priority: 3
      capabilities:
        - "load_testing"
        - "stress_testing"
        - "performance_analysis"

  communication:
    protocol: "message_bus"
    message_format: "json"
    encryption: true

  consensus:
    algorithm: "weighted"
    quorum: 0.6
    timeout_seconds: 30

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 9: MEMORY
# ─────────────────────────────────────────────────────────────────────────────────
memory:
  type: "persistent"
  retention: "90_days"
  storage: "supabase"
  max_tokens: 32000
  indexing: "hnsw"
  retrieval_strategy: "hybrid"

  chunking:
    strategy: "semantic"
    size: 1000
    overlap: 200

  encryption:
    at_rest: true
    in_transit: true
    algorithm: "aes-256-gcm"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 10: REASONING
# ─────────────────────────────────────────────────────────────────────────────────
reasoning:
  model: "claude-sonnet-4-20250514"
  depth: 5
  multi_hop: true
  confidence_threshold: 0.80
  fallback_to_traditional: true

  llm_settings:
    temperature: 0.15
    max_tokens: 16000
    top_p: 0.85
    frequency_penalty: 0.1
    presence_penalty: 0.1

  chain_of_thought:
    enabled: true
    format: "xml"
    visible_to_user: false

  planning:
    enabled: true
    max_steps: 20
    revision_allowed: true

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 11: TOOLS
# ─────────────────────────────────────────────────────────────────────────────────
tools:
  terminal:
    enabled: true
    shell: "bash"
    sudo: false
    allowed_commands:
      - "npm"
      - "npx"
      - "pnpm"
      - "jest"
      - "vitest"
      - "playwright"
      - "cypress"
      - "pytest"
      - "git"
    blocked_commands:
      - "rm -rf /"
      - "sudo"

  filesystem:
    read: "unlimited"
    write: "limited"
    execute: false
    allowed_paths:
      - "/tests"
      - "/src"
      - "/__tests__"
      - "/coverage"
    blocked_paths:
      - "/.env"
      - "/secrets"

  apis:
    rest: true
    graphql: true
    websocket: false

  code_execution:
    enabled: true
    languages:
      - "javascript"
      - "typescript"
      - "python"
    sandbox: true
    timeout_seconds: 120

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 12: SAFETY
# ─────────────────────────────────────────────────────────────────────────────────
safety:
  guardrails:
    financial_limit_enforcement: true
    pii_protection: true
    legal_compliance: true
    rate_limiting: true
    content_moderation: false

  emergency_controls:
    abort_command: "ABORT QA"
    rollback_command: "ROLLBACK TESTS"
    kill_switch_enabled: true

  monitoring:
    alert_threshold: "medium"
    audit_level: "important"
    retention_days: 90

  circuit_breaker:
    enabled: true
    failure_threshold: 5
    reset_timeout_seconds: 300

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 13: POLICIES
# ─────────────────────────────────────────────────────────────────────────────────
policies:
  default_policy: "quality_first"
  enforcement_mode: "enforce"

  policies:
    - name: "quality_first"
      description: "Enforce quality standards before release"
      priority: 1
      enabled: true
      rules:
        - condition: "coverage < 80%"
          action: "deny"
          message: "Test coverage must be at least 80%"
        - condition: "failing_tests > 0"
          action: "deny"
          message: "All tests must pass before release"
        - condition: "critical_bugs > 0"
          action: "require_approval"
          message: "Critical bugs require approval to proceed"

    - name: "automation_required"
      description: "Require test automation for features"
      priority: 2
      enabled: true
      rules:
        - condition: "new_feature && no_tests"
          action: "deny"
          message: "New features must have automated tests"

  violation_handling:
    log: true
    notify:
      - "#qa-alerts"
    block: true
    escalate_after: 3

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 14: TRIGGERS
# ─────────────────────────────────────────────────────────────────────────────────
triggers:
  scheduled:
    - name: "nightly_regression"
      schedule: "0 2 * * *"
      action: "run_full_regression"
      enabled: true
      timezone: "UTC"
      timeout_seconds: 7200

    - name: "coverage_report"
      schedule: "0 8 * * 1"
      action: "generate_coverage_report"
      enabled: true
      timezone: "UTC"

  webhooks:
    - name: "pr_test_trigger"
      path: "/webhooks/qa/pr"
      method: "POST"
      action: "run_pr_tests"
      authentication: "hmac"
      rate_limit: 100

  events:
    - name: "on_pr_opened"
      source: "github"
      event_type: "pull_request.opened"
      action: "trigger_test_suite"
      debounce_seconds: 5

    - name: "on_push_main"
      source: "github"
      event_type: "push"
      filter: "branch == 'main'"
      action: "trigger_full_regression"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 15: INTEGRATIONS
# ─────────────────────────────────────────────────────────────────────────────────
integrations:
  api_keys:
    github:
      env_var: "GITHUB_TOKEN"
      header_name: "Authorization"
      prefix: "Bearer"

    codecov:
      env_var: "CODECOV_TOKEN"

  notifications:
    slack:
      webhook_url_env: "SLACK_WEBHOOK_URL"
      default_channel: "#qa-notifications"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 16: OBSERVABILITY
# ─────────────────────────────────────────────────────────────────────────────────
observability:
  logging:
    level: "info"
    format: "json"
    destination: "cloud"
    redact_pii: true

  metrics:
    enabled: true
    provider: "prometheus"
    push_interval_seconds: 60
    custom_metrics:
      - name: "qa_test_coverage"
        type: "gauge"
        description: "Current test coverage percentage"
        labels: ["project", "module"]
      - name: "qa_tests_executed"
        type: "counter"
        description: "Total tests executed"
        labels: ["type", "status"]
      - name: "qa_defects_found"
        type: "counter"
        description: "Defects found by testing"
        labels: ["severity", "component"]

  tracing:
    enabled: true
    provider: "otel"
    sample_rate: 0.5
    propagation: "w3c"

  alerting:
    enabled: true
    channels:
      - "slack"
      - "pagerduty"
    rules:
      - name: "coverage_drop"
        condition: "coverage_delta < -5%"
        severity: "high"
      - name: "test_failure_spike"
        condition: "failure_rate > 10%"
        severity: "critical"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 17: CONTEXT
# ─────────────────────────────────────────────────────────────────────────────────
context:
  system_prompt: |
    You are the QA Pack Manager, the central orchestrator for all quality assurance activities.

    Your responsibilities:
    1. Coordinate test agents (Test, Automation, Regression, Performance)
    2. Enforce quality gates and coverage requirements
    3. Manage test strategies and prioritization
    4. Generate quality reports and metrics
    5. Delegate tasks to specialized QA agents

    Quality principles:
    - Zero defects escape to production
    - Test coverage must meet thresholds (80% minimum)
    - Automation ratio should be high (>70%)
    - Early detection over late detection

    When delegating:
    - qa_test: For test generation and coverage analysis
    - qa_automation: For framework setup and CI/CD integration
    - qa_regression: For regression suite management and impact analysis
    - qa_performance: For load, stress, and performance testing

  instructions:
    - "Always verify test coverage before approving changes"
    - "Prioritize critical path testing"
    - "Enforce quality gates strictly"
    - "Generate actionable reports"
    - "Coordinate with development teams"

  context_window:
    max_tokens: 32000
    reserved_for_output: 4000
    prioritization: "relevance"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 18: EVALS
# ─────────────────────────────────────────────────────────────────────────────────
evals:
  enabled: true
  suites:
    - "qa_pack_regression"
    - "quality_gate_enforcement"
    - "agent_coordination"
  golden_tasks_path: "/evals/golden_tasks/qa"
  adversarial_path: "/evals/adversarial/qa"

  metrics:
    accuracy_threshold: 0.90
    latency_p99_ms: 5000
    cost_per_task_max: 0.50
    safety_score_min: 0.95

  regression:
    enabled: true
    max_regression_percent: 5

  notifications:
    on_failure:
      - "#qa-evals"
    on_regression:
      - "#qa-evals"
      - "#engineering-alerts"
