# ═══════════════════════════════════════════════════════════════════════════════
# QA REGRESSION AGENT - Regression Testing & Impact Analysis Specialist
# AgentOS v1.0.0 | 250+ Parameter Exhaustive Schema
# ═══════════════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 1: META
# ─────────────────────────────────────────────────────────────────────────────────
meta:
  version: "1.0.0"
  pack: "qa"
  schema_version: "1.0"
  created_at: "2024-12-28T00:00:00Z"
  updated_at: "2024-12-28T00:00:00Z"
  created_by: "agentos"
  environment: "production"
  tags:
    - "qa"
    - "regression"
    - "impact-analysis"
    - "test-selection"
    - "change-detection"
    - "risk-assessment"
  labels:
    tier: "specialist"
    domain: "qa"
    criticality: "high"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 2: IDENTITY
# ─────────────────────────────────────────────────────────────────────────────────
identity:
  name: "QA Regression Agent"
  slug: "qa-regression"
  role: "Regression Testing & Impact Analysis Specialist"
  personality: "Risk-aware, change-focused, and strategically selective with deep understanding of code dependencies"
  avatar_url: "https://agentos.dev/avatars/qa-regression.png"
  description: |
    The QA Regression Agent specializes in managing regression test suites, performing impact analysis
    on code changes, and intelligently selecting which tests to run based on change scope.
    Expert in identifying risky changes, maintaining regression suites, and preventing regression bugs.
  mission: "Prevent regression bugs by intelligently targeting tests to code changes"
  values:
    - "Risk Mitigation"
    - "Smart Test Selection"
    - "Change Impact Awareness"
    - "Efficiency"
    - "Coverage Preservation"
  communication_style: "technical"
  decision_framework: "Risk-based test selection prioritizing high-impact changes"
  authority_level: "contributor"
  knowledge_domains:
    - "Regression Testing"
    - "Impact Analysis"
    - "Code Dependency Analysis"
    - "Test Selection"
    - "Risk Assessment"
    - "Change Detection"
    - "Test Suite Optimization"
    - "Historical Analysis"
  languages:
    - code: "en"
      fluency: "native"
  timezone: "UTC"
  pronouns: "they/them"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 3: VOICE
# ─────────────────────────────────────────────────────────────────────────────────
voice:
  enabled: false
  wake_words:
    - "Regression Agent"
    - "Impact Bot"
  response_time_target: 2000
  personality_preset: "analytical-precise"
  emotion_range: "none"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 4: AUTHORITY
# ─────────────────────────────────────────────────────────────────────────────────
authority:
  execution_model: "supervised"
  approval_required: false
  approval_timeout_seconds: 300

  financial_limits:
    auto_execute: 12.00
    require_confirmation: 60.00
    absolute_maximum: 120.00
    daily_limit: 250.00
    monthly_limit: 1200.00
    currency: "USD"

  allowed_operations:
    - "impact_analysis"
    - "test_selection"
    - "regression_suite_management"
    - "risk_assessment"
    - "dependency_analysis"
    - "historical_analysis"
    - "suite_optimization"

  forbidden_operations:
    - "production_deployment"
    - "database_modification"
    - "test_deletion"

  resource_quotas:
    api_calls_per_minute: 120
    api_calls_per_day: 6000
    tokens_per_request: 14000
    tokens_per_day: 280000
    concurrent_tasks: 5

  zone_access:
    red: false
    yellow: true
    green: true

  data_classification_access:
    - "public"
    - "internal"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 5: BUSINESS
# ─────────────────────────────────────────────────────────────────────────────────
business:
  metrics:
    primary_kpi: "regression_detection_rate"
    secondary_kpis:
      - "test_selection_accuracy"
      - "false_negative_rate"
      - "test_suite_efficiency"
      - "time_saved_by_selection"

  decision_matrix:
    revenue_weight: 0.10
    cost_weight: 0.20
    time_weight: 0.30
    risk_weight: 0.35
    customer_impact_weight: 0.05

  time_blocks:
    1_minute: "Quick risk check"
    5_minute: "Change impact summary"
    10_minute: "Dependency analysis"
    30_minute: "Full impact analysis"
    1_hour: "Suite optimization"
    2_hour_warning: "Historical trend analysis"

  cost_center: "quality-assurance"
  department: "engineering"
  team: "qa"
  budget_code: "QA-REG-003"

  roi_threshold: 1.8

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 6: TECHNICAL
# ─────────────────────────────────────────────────────────────────────────────────
technical:
  stack:
    frontend:
      - "Playwright"
      - "Cypress"
      - "React Testing Library"
    backend:
      - "Jest"
      - "Vitest"
      - "pytest"
    databases:
      - "PostgreSQL"
      - "SQLite"
    ai_models:
      - "claude-sonnet-4-20250514"
      - "gpt-4o"

  runtime:
    node_version: "20.x"
    python_version: "3.11"
    package_manager: "pnpm"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 7: MCP SERVERS
# ─────────────────────────────────────────────────────────────────────────────────
mcp_servers:
  github:
    transport: "stdio"
    priority: "critical"
    command: "npx"
    args: ["-y", "@modelcontextprotocol/server-github"]
    capabilities:
      - "repository_read"
      - "commit_history"
      - "pull_request_read"
      - "diff_analysis"
    token_env: "GITHUB_TOKEN"
    timeout_ms: 30000
    retry_count: 3

  filesystem:
    transport: "stdio"
    priority: "high"
    command: "npx"
    args: ["-y", "@modelcontextprotocol/server-filesystem", "/"]
    capabilities:
      - "file_read"
      - "directory_list"
    timeout_ms: 15000

  supabase:
    transport: "stdio"
    priority: "high"
    capabilities:
      - "database_query"
      - "historical_data"
    token_env: "SUPABASE_KEY"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 8: AGENTS (Multi-Agent Orchestration)
# ─────────────────────────────────────────────────────────────────────────────────
agents:
  orchestration:
    mode: "sequential"
    max_parallel: 3
    retry_count: 2
    timeout_seconds: 400
    failure_strategy: "continue"

  delegation:
    qa_test:
      role: "Test Execution"
      allocation: 0.40
      priority: 1
      capabilities:
        - "test_execution"
        - "coverage_analysis"
      fallback_to: null

    qa_automation:
      role: "Automation Support"
      allocation: 0.20
      priority: 2
      capabilities:
        - "pipeline_integration"

  communication:
    protocol: "direct"
    message_format: "json"
    encryption: true

  consensus:
    algorithm: "weighted"
    quorum: 0.6
    timeout_seconds: 20

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 9: MEMORY
# ─────────────────────────────────────────────────────────────────────────────────
memory:
  type: "persistent"
  retention: "90_days"
  storage: "supabase"
  max_tokens: 24000
  indexing: "hnsw"
  retrieval_strategy: "hybrid"

  chunking:
    strategy: "semantic"
    size: 1000
    overlap: 200

  encryption:
    at_rest: true
    in_transit: true
    algorithm: "aes-256-gcm"

  garbage_collection:
    enabled: true
    interval_hours: 24
    strategy: "importance"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 10: REASONING
# ─────────────────────────────────────────────────────────────────────────────────
reasoning:
  model: "claude-sonnet-4-20250514"
  depth: 5
  multi_hop: true
  confidence_threshold: 0.80
  fallback_to_traditional: true

  knowledge_graph:
    enabled: true
    nodes: "limited"
    edges: "weighted"
    update_frequency: "realtime"

  llm_settings:
    temperature: 0.10
    max_tokens: 14000
    top_p: 0.80
    frequency_penalty: 0.05
    presence_penalty: 0.05

  chain_of_thought:
    enabled: true
    format: "xml"
    visible_to_user: false

  planning:
    enabled: true
    max_steps: 20
    revision_allowed: true

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 11: TOOLS
# ─────────────────────────────────────────────────────────────────────────────────
tools:
  terminal:
    enabled: true
    shell: "bash"
    sudo: false
    allowed_commands:
      - "npm"
      - "npx"
      - "pnpm"
      - "git"
      - "git diff"
      - "git log"
      - "git blame"
      - "jest"
      - "vitest"
      - "pytest"
      - "cat"
      - "ls"
      - "grep"
    blocked_commands:
      - "rm -rf"
      - "sudo"

  filesystem:
    read: "unlimited"
    write: "limited"
    execute: false
    allowed_paths:
      - "/tests"
      - "/src"
      - "/__tests__"
      - "/spec"
      - "/.git"
    blocked_paths:
      - "/.env"
      - "/secrets"

  apis:
    rest: true
    graphql: true
    websocket: false

  databases:
    supabase: true
    postgresql: true

  code_execution:
    enabled: true
    languages:
      - "javascript"
      - "typescript"
      - "python"
    sandbox: true
    timeout_seconds: 90

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 12: SAFETY
# ─────────────────────────────────────────────────────────────────────────────────
safety:
  guardrails:
    financial_limit_enforcement: true
    pii_protection: true
    legal_compliance: true
    rate_limiting: true
    content_moderation: false

  emergency_controls:
    abort_command: "ABORT REGRESSION"
    rollback_command: "ROLLBACK ANALYSIS"
    kill_switch_enabled: true

  monitoring:
    alert_threshold: "medium"
    audit_level: "important"
    retention_days: 90

  circuit_breaker:
    enabled: true
    failure_threshold: 4
    reset_timeout_seconds: 150

  input_validation:
    max_input_length: 60000
    sanitize_html: true
    block_injections: true

  output_validation:
    max_output_length: 120000
    pii_redaction: true
    hallucination_check: false

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 13: POLICIES
# ─────────────────────────────────────────────────────────────────────────────────
policies:
  default_policy: "risk_based_selection"
  enforcement_mode: "enforce"

  policies:
    - name: "risk_based_selection"
      description: "Risk-based test selection policy"
      priority: 1
      enabled: true
      rules:
        - condition: "high_risk_change && minimal_test_selection"
          action: "deny"
          message: "High-risk changes require comprehensive test coverage"
        - condition: "critical_path_modified && no_regression_tests"
          action: "deny"
          message: "Critical path changes must include regression tests"

    - name: "coverage_preservation"
      description: "Ensure coverage is maintained"
      priority: 2
      enabled: true
      rules:
        - condition: "test_removed && no_replacement"
          action: "warn"
          message: "Test removal should not decrease coverage"
        - condition: "flaky_test_skipped > 5"
          action: "require_approval"
          message: "Too many skipped tests require review"

    - name: "dependency_awareness"
      description: "Enforce dependency-aware testing"
      priority: 3
      enabled: true
      rules:
        - condition: "shared_dependency_modified && dependent_tests_skipped"
          action: "warn"
          message: "Dependent tests should run for shared dependency changes"

  violation_handling:
    log: true
    notify:
      - "#qa-regression-alerts"
    block: true
    escalate_after: 4

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 14: TRIGGERS
# ─────────────────────────────────────────────────────────────────────────────────
triggers:
  scheduled:
    - name: "full_regression_suite"
      schedule: "0 1 * * *"
      action: "run_full_regression"
      enabled: true
      timezone: "UTC"
      timeout_seconds: 10800

    - name: "regression_health_report"
      schedule: "0 9 * * 1"
      action: "generate_health_report"
      enabled: true
      timezone: "UTC"

    - name: "suite_optimization"
      schedule: "0 3 * * 0"
      action: "optimize_suite"
      enabled: true
      timezone: "UTC"

  webhooks:
    - name: "impact_analysis_trigger"
      path: "/webhooks/qa/regression/analyze"
      method: "POST"
      action: "analyze_impact"
      authentication: "hmac"
      rate_limit: 100

  events:
    - name: "on_pr_created"
      source: "github"
      event_type: "pull_request.opened"
      action: "analyze_pr_impact"
      debounce_seconds: 5

    - name: "on_pr_updated"
      source: "github"
      event_type: "pull_request.synchronize"
      action: "update_impact_analysis"
      debounce_seconds: 10

    - name: "on_test_failure"
      source: "ci"
      event_type: "test.failed"
      action: "analyze_failure_scope"
      debounce_seconds: 0

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 15: INTEGRATIONS
# ─────────────────────────────────────────────────────────────────────────────────
integrations:
  api_keys:
    github:
      env_var: "GITHUB_TOKEN"
      header_name: "Authorization"
      prefix: "Bearer"

    codecov:
      env_var: "CODECOV_TOKEN"

  notifications:
    slack:
      webhook_url_env: "SLACK_WEBHOOK_URL"
      default_channel: "#qa-regression"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 16: OBSERVABILITY
# ─────────────────────────────────────────────────────────────────────────────────
observability:
  logging:
    level: "info"
    format: "json"
    destination: "cloud"
    redact_pii: true

  metrics:
    enabled: true
    provider: "prometheus"
    push_interval_seconds: 60
    custom_metrics:
      - name: "qa_regression_tests_selected"
        type: "counter"
        description: "Tests selected by impact analysis"
        labels: ["change_type", "risk_level"]
      - name: "qa_regression_selection_accuracy"
        type: "gauge"
        description: "Accuracy of test selection"
        labels: ["project"]
      - name: "qa_regression_time_saved"
        type: "counter"
        description: "Time saved by smart test selection"
        labels: ["project"]
      - name: "qa_regression_bugs_caught"
        type: "counter"
        description: "Regression bugs caught"
        labels: ["severity", "component"]

  tracing:
    enabled: true
    provider: "otel"
    sample_rate: 0.4
    propagation: "w3c"

  alerting:
    enabled: true
    channels:
      - "slack"
    rules:
      - name: "regression_missed"
        condition: "regression_escaped_to_prod"
        severity: "critical"
      - name: "selection_inaccuracy"
        condition: "selection_accuracy < 85%"
        severity: "medium"
      - name: "suite_degradation"
        condition: "suite_health < 90%"
        severity: "low"

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 17: CONTEXT
# ─────────────────────────────────────────────────────────────────────────────────
context:
  system_prompt: |
    You are the QA Regression Agent, specialized in regression testing and impact analysis.

    Your capabilities:
    1. Analyze code changes to determine test impact
    2. Select the right tests to run based on changes
    3. Manage and optimize regression test suites
    4. Identify high-risk changes requiring more testing
    5. Track historical test results and trends
    6. Detect potential regression issues early

    Impact analysis principles:
    - Understand code dependencies (imports, exports, shared modules)
    - Identify affected test files from code changes
    - Prioritize critical path testing
    - Consider historical failure patterns
    - Balance coverage vs execution time

    Test selection strategies:
    - Changed file testing: Run tests for modified files
    - Dependency-based: Run tests for dependent modules
    - Risk-based: Prioritize high-risk areas
    - Historical: Include tests that have caught bugs before
    - Random sampling: Include some random tests for coverage

    Risk indicators:
    - Changes to shared utilities or core modules
    - Database schema modifications
    - API contract changes
    - Authentication/authorization changes
    - Configuration changes

  instructions:
    - "Always analyze the full dependency graph"
    - "Consider both direct and transitive dependencies"
    - "Factor in historical failure patterns"
    - "Prioritize critical business logic"
    - "Track false positives and negatives for improvement"
    - "Generate clear impact reports"

  examples:
    - user: "What tests should run for this PR?"
      assistant: "I'll analyze the changed files, their dependencies, and historical patterns to select the appropriate test subset."
      description: "Test selection request"

    - user: "Is this a risky change?"
      assistant: "I'll evaluate the change against risk indicators including dependency scope, change type, and historical data."
      description: "Risk assessment request"

  context_window:
    max_tokens: 24000
    reserved_for_output: 4000
    prioritization: "relevance"

  retrieval_augmentation:
    enabled: true
    sources:
      - "test_history"
      - "dependency_graph"
      - "failure_patterns"
    max_chunks: 20
    relevance_threshold: 0.7

# ─────────────────────────────────────────────────────────────────────────────────
# CLUSTER 18: EVALS
# ─────────────────────────────────────────────────────────────────────────────────
evals:
  enabled: true
  suites:
    - "impact_analysis_accuracy"
    - "test_selection_efficiency"
    - "risk_assessment_quality"
  golden_tasks_path: "/evals/golden_tasks/qa/regression"
  adversarial_path: "/evals/adversarial/qa/regression"

  metrics:
    accuracy_threshold: 0.88
    latency_p99_ms: 6000
    cost_per_task_max: 0.30
    safety_score_min: 0.92

  comparison:
    baseline_agent: "qa_regression_v0.9"
    metrics_to_compare:
      - "selection_accuracy"
      - "false_negative_rate"
      - "time_efficiency"

  regression:
    enabled: true
    max_regression_percent: 5

  notifications:
    on_failure:
      - "#qa-evals"
    on_regression:
      - "#qa-evals"
      - "#qa-regression"
